config/routes.rb
Flatsoft::Application.routes.draw do
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  resources :events, except: [:index, :edit]
  devise_for :users

  root :to => 'calendar#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_event_calendar
  attr_accessible :name, :start_at, :end_at, :user, :repeat
  validates_presence_of :name, :start_at, :end_at
  #repeat every_day: 1, every_week: 2, every_month: 3, every_year: 4
  def repeat=(period)
    case period
    when 'day'
      self[:repeat] = EventHelper::DAY
    when 'week'
      self[:repeat] = EventHelper::WEEK
    when 'month' 
      self[:repeat] = EventHelper::MONTH
    when 'year' 
      self[:repeat] = EventHelper::YEAR
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
  attr_accessible :username

  def name
  	self.username || self.email
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  
  def index
    @show_all = params[:show_all]
    @month = (params[:month] || (Time.zone || Time).now.month).to_i
    @year = (params[:year] || (Time.zone || Time).now.year).to_i
    @shown_month = Date.civil(@year, @month)

    if @show_all == "false"
      @event_strips = Event.event_strips_for_month(@shown_month, conditions: ['user_id = ?', current_user.id])
    else
      @event_strips = Event.event_strips_for_month(@shown_month)
    end
  end

end

app/controllers/events_controller.rb
#encoding: utf-8
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def create
    if params[:event][:user] == 'current'
      params[:event][:user] = current_user
    else
      params[:event][:user] = nil
    end
    @event = Event.new(params[:event])
    if @event.save
      flash[:success] = "Событие успешно создано!"
      redirect_to calendar_path
    else
      render 'new'
    end
  end

  def show
    @event = Event.find_by_id(params[:id])
  end

  def update
    if params[:event][:user] == 'current'
      params[:event][:user] = current_user
    else
      params[:event][:user] = nil
    end
    @event = Event.find_by_id(params[:id])
    if @event.update_attributes(params[:event])
      flash[:notice] = "Событие успешно обновлено!"
      redirect_to calendar_path
    else
      render 'new'
    end
  end

  def destroy
    Event.find_by_id(params[:id]).destroy
    redirect_to calendar_path, notice: "Событие удалено!" 
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
    return page_title
  end

  def current_name
  	current_user.username || current_user.email
  end

end

app/helpers/calendar_helper.rb
module CalendarHelper
  def month_link(month_date)
    link_to(I18n.localize(month_date, :format => "%B"), {:month => month_date.month, :year => month_date.year, :show_all => @show_all})
  end

  def show_for_all
  end

  def for_current_user
  end
  
  # custom options for this calendar
  def event_calendar_opts
    { 
      :year => @year,
      :month => @month,
      :event_strips => @event_strips,
      :month_name_text => I18n.localize(@shown_month, :format => "%B %Y"),
      :previous_month_text => "<< " + month_link(@shown_month.prev_month),
      :next_month_text => month_link(@shown_month.next_month) + " >>"    }
  end

  def event_calendar
    # args is an argument hash containing :event, :day, and :args[:event]
    calendar event_calendar_opts do |args|
      event = args[:event]
      if event.user
        %(<a href="/events/#{event.id}" title="#{h(event.name)} - #{h(event.user.name)}">#{h(event.name)} - #{h(event.user.name)}</a>)
      else
        %(<a href="/events/#{event.id}" title="#{h(event.name)}">#{h(event.name)}</a>)
      end
    end
  end
end

app/helpers/event_helper.rb
module EventHelper
  DAY = 1
  WEEK = 2
  MONTH = 3
  YEAR = 4
  def for_user?(event)
    return true if event.id && Event.find(event).user
    return false
  end
end

app/views/calendar/index.html.erb
<!-- Probably move the stylesheet to you layout. Also make sure you include the javascript. -->
<%= stylesheet_link_tag "event_calendar" %>

<h1><%= title("Календарь") %></h1>
<p><%= link_to raw("<i class='icon-plus'></i> Добавить событие"), new_event_path, class: "btn" %> 
	Показать: 
	<% if params[:show_all] == 'false' %>
		<%= link_to "все", calendar_path(year: @year, month: @month, show_all: true) %>
	<% else %>
		<%= link_to "только свои", calendar_path(year: @year, month: @month, show_all: false) %>
	<% end %>
</p>

<%= raw(event_calendar) %>

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <%= render 'layouts/error', object: f.object %>
  <div class="control-group">
    <%= f.label :name, class: "control-label" %> 
    <div class="controls">
      <%= f.text_field :name, class: "input-xlarge", required: true %>
    </div>
  </div>
    <div class="control-group">
    <%= f.label :start_at, class: "control-label" %> 
    <div class="controls">
      <%= f.text_field :start_at, class: "input-xlarge", required: true %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :end_at, class: "control-label" %> 
    <div class="controls">
      <%= f.text_field :end_at, class: "input-xlarge", required: true %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :user, "Доступно:", class: "control-label" %> 
    <div class="controls">
      <label class="radio">
        <%= f.radio_button(:user, 'current', checked: for_user?(@event) ) %>
        <%= f.label(:user_current, current_name) %>
      </label>
      <label class="radio">
        <%= f.radio_button(:user, 'any', checked: !for_user?(@event) ) %>
        <%= f.label(:user_any, 'Всем') %>
      </label>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :repeat, "Повторять", class: "control-label" %>
    <div class="controls">
      <label class="radio">
        <%= f.radio_button(:repeat, 'day', checked: @event.repeat == EventHelper::DAY) %>
        <%= f.label(:repeat_day, 'Каждый день') %>
      </label>
      <label class="radio">
        <%= f.radio_button(:repeat, 'week', checked: @event.repeat == EventHelper::WEEK) %>
        <%= f.label(:repeat_week, 'Каждую неделю') %>
      </label>
      <label class="radio">
        <%= f.radio_button(:repeat, 'month', checked: @event.repeat == EventHelper::MONTH) %>
        <%= f.label(:repeat_month, 'Каждый месяц') %>
      </label>
      <label class="radio">
        <%= f.radio_button(:repeat, 'year', checked: @event.repeat == EventHelper::YEAR) %>
        <%= f.label(:repeat_year, 'Каждый год') %>
      </label>
    </div>
  <div><%= f.submit "Сохранить", class: "btn btn-primary", id: "create" %></div>  

<% end %>

app/views/events/new.html.erb
<h2> <%= title("Новое событие") %> </h2>

<%= render 'form' %>

<%= link_to 'Назад', calendar_path %>

app/views/events/show.html.erb
<h2> <%= title("Редактировать событие") %> </h2>

<%= render 'form' %>

<%= link_to 'Удалить', event_path(@event), method: :delete, data: {confirm: "Вы уверены?"} %>
<%= link_to 'Назад', calendar_path %>

app/views/layouts/_error.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      При сохранении произошли <%= pluralize(object.errors.count, "ошибки") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>Календарь для flatsoft</small> 
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Календарь", root_path,  class: "brand" %>
      <div class="container nav-collapse">
        <ul class="nav pull-right">
          <li class="divider-vertical"></li>
          <% if user_signed_in? %>
            <li><%= link_to current_user.username || current_user.email, edit_user_registration_path %></li>
            <li><%= link_to "Выход", destroy_user_session_path, method: "delete" %>
          <% else %>
            <li><%= link_to "Вход", new_user_session_path %></li>
            <li><%= link_to "Регистрация", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Календарь - <%= yield(:title) || "Flatsoft" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% unless flash[:notice].blank? %>
        <div class="alert alert-info">
          <%= content_tag :div, flash[:notice] %>
        </div>
      <% end %>

      <% unless flash[:error].blank? %>
        <div class="alert alert-error">
          <%= content_tag :div, flash[:error] %>
        </div>
      <% end %>

      <% unless flash[:alert].blank? %>
        <div class="alert alert-error">
          <%= content_tag :div, flash[:alert] %>
        </div>
      <% end %>
      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            <!-- <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                  <li><%= link_to "Link1", "/path1"  %></li>
                  <li><%= link_to "Link2", "/path2"  %></li>
                  <li><%= link_to "Link3", "/path3"  %></li>
                </ul>
              </div>
            </div>-->
        </div><!--/row-->
      </div><!--/content-->


      <%= render 'layouts/footer' %>
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>